/*
Req 9
Pour chaque code session et sigle d’un cours, retourner le sigle du cours
et son titre et la différence entre la meilleure et la plus mauvaise note pour un cours donné.
*/
SELECT BASE.SIGLE, BASE.TITRE, MAX(DIFF) AS DIFF FROM (
    SELECT
        INSCRIPTION.CODESESSION, INSCRIPTION.SIGLE, COURS.TITRE
    FROM
        INSCRIPTION, GROUPECOURS, COURS
    WHERE
        INSCRIPTION.SIGLE = GROUPECOURS.SIGLE
    AND
        INSCRIPTION.NOGROUPE = GROUPECOURS.NOGROUPE
    AND
        INSCRIPTION.CODESESSION = GROUPECOURS.CODESESSION
    AND
        GROUPECOURS.SIGLE = COURS.SIGLE
) BASE
JOIN (
    SELECT
        MAX(NOTE), MIN(NOTE), MAX(NOTE) - MIN(NOTE) AS DIFF, SIGLE, NOGROUPE, CODESESSION
    FROM
        INSCRIPTION
    GROUP BY
        SIGLE, NOGROUPE, CODESESSION
) NOTES 
ON
    NOTES.SIGLE = BASE.SIGLE
GROUP BY
    BASE.SIGLE, BASE.TITRE;