/*
Req 1
Donnez les informations sans répétition des sigles, titres des cours pris par l’étudiant
Lavoie Paul ainsi que les noms des professeurs qui donnent ces cours.
*/
SELECT
  DISTINCT(COURS.SIGLE), COURS.TITRE, PROFESSEUR.NOM, PROFESSEUR.PRENOM
FROM
  COURS, GROUPECOURS, PROFESSEUR, INSCRIPTION
WHERE
  COURS.SIGLE = GROUPECOURS.SIGLE
AND
  GROUPECOURS.CODEPROFESSEUR = PROFESSEUR.CODEPROFESSEUR
AND
  INSCRIPTION.SIGLE = GROUPECOURS.SIGLE
AND
  INSCRIPTION.CODEPERMANENT = 'LAVP08087001';
