/*
Req 5
On cherche les codes et les noms des professeurs, sans répétition:
- qui ont enseigné au plus un cours offert à la session 32003
- ou au moins un cours offert aux deux sessions (toutes les deux) dont les codes sont 12004 et 22005.
*/
SELECT CODEPROFESSEUR, NOM, PRENOM FROM (
    SELECT
        COUNT(*) AS COMTECOURS, GROUPECOURS.CODEPROFESSEUR, PROFESSEUR.NOM, PROFESSEUR.PRENOM
    FROM
        SESSIONUQAM, GROUPECOURS, PROFESSEUR
    WHERE
        SESSIONUQAM.CODESESSION = '32003'
    AND
        SESSIONUQAM.CODESESSION = GROUPECOURS.CODESESSION
    AND
        GROUPECOURS.CODEPROFESSEUR = PROFESSEUR.CODEPROFESSEUR
    GROUP BY
        GROUPECOURS.CODEPROFESSEUR, PROFESSEUR.NOM, PROFESSEUR.PRENOM
)
WHERE COMTECOURS <= 1;