SET ECHO ON;
SET VERIFY OFF;
SPOOL TP1.out;
-- Req 1
SELECT
  DISTINCT(COURS.SIGLE), COURS.TITRE, PROFESSEUR.NOM, PROFESSEUR.PRENOM
FROM
  COURS, GROUPECOURS, PROFESSEUR, INSCRIPTION
WHERE
  COURS.SIGLE = GROUPECOURS.SIGLE
AND
  GROUPECOURS.CODEPROFESSEUR = PROFESSEUR.CODEPROFESSEUR
AND
  INSCRIPTION.SIGLE = GROUPECOURS.SIGLE
AND
  INSCRIPTION.CODEPERMANENT = 'LAVP08087001';
-- Req 2
SELECT
  DISTINCT(GROUPECOURS.CODEPROFESSEUR), PROFESSEUR.NOM, PROFESSEUR.PRENOM
FROM
  GROUPECOURS, PROFESSEUR
WHERE ((
    (SIGLE = 'INF3180' OR SIGLE = 'INF2110') AND
    CODESESSION = '12004'
) OR (
    (SIGLE = 'INF1130' OR SIGLE = 'INF1110') AND
    CODESESSION = '32003'
)) AND
  GROUPECOURS.CODEPROFESSEUR = PROFESSEUR.CODEPROFESSEUR;
-- Req 3
SELECT
    INSCRIPTION.CODEPERMANENT, INSCRIPTION2.CODEPERMANENT2,
    INSCRIPTION.SIGLE, INSCRIPTION.CODESESSION, INSCRIPTION.NOTE
FROM
    INSCRIPTION
JOIN
    (SELECT
        CODEPERMANENT AS CODEPERMANENT2, NOTE, SIGLE, CODESESSION
    FROM
        INSCRIPTION) INSCRIPTION2
ON (
    INSCRIPTION.NOTE = INSCRIPTION2.NOTE AND
    INSCRIPTION.SIGLE = INSCRIPTION2.SIGLE AND
    INSCRIPTION.CODESESSION = INSCRIPTION2.CODESESSION
)
WHERE
    INSCRIPTION.CODEPERMANENT != INSCRIPTION2.CODEPERMANENT2;
-- Req 4
SELECT
    INSCRIPTION.CODEPERMANENT, ETUDIANT.NOM AS NOMETUDIANT,
    ETUDIANT.PRENOM AS PRENOMETUDIANT, INSCRIPTION.SIGLE
FROM
    INSCRIPTION, GROUPECOURS, PROFESSEUR, ETUDIANT
WHERE
    INSCRIPTION.SIGLE LIKE 'INF%'
AND
    (INSCRIPTION.CODESESSION = '32003' OR INSCRIPTION.CODESESSION = '12004')
AND
    PROFESSEUR.NOM = 'De Vinci'
AND
    INSCRIPTION.CODEPERMANENT = ETUDIANT.CODEPERMANENT
AND
    INSCRIPTION.SIGLE = GROUPECOURS.SIGLE
AND
    INSCRIPTION.CODESESSION = GROUPECOURS.CODESESSION
AND
    INSCRIPTION.NOGROUPE = GROUPECOURS.NOGROUPE
AND
    GROUPECOURS.CODEPROFESSEUR = PROFESSEUR.CODEPROFESSEUR
AND
    INSCRIPTION.DATEABANDON IS NULL;
-- Req 5
SELECT CODEPROFESSEUR, NOM, PRENOM FROM (
    SELECT
        COUNT(*) AS COMTECOURS, GROUPECOURS.CODEPROFESSEUR, PROFESSEUR.NOM, PROFESSEUR.PRENOM
    FROM
        SESSIONUQAM, GROUPECOURS, PROFESSEUR
    WHERE
        SESSIONUQAM.CODESESSION = '32003'
    AND
        SESSIONUQAM.CODESESSION = GROUPECOURS.CODESESSION
    AND
        GROUPECOURS.CODEPROFESSEUR = PROFESSEUR.CODEPROFESSEUR
    GROUP BY
        GROUPECOURS.CODEPROFESSEUR, PROFESSEUR.NOM, PROFESSEUR.PRENOM
)
WHERE
  COMTECOURS <= 1;
-- Req 6
SELECT
    CODEPERMANENT, NOM, PRENOM
FROM
    ETUDIANT
WHERE
    NOM LIKE 'T%' OR NOM LIKE '%a%';
-- Req 7
SELECT
    DISTINCT(SIGLE)
FROM
    GROUPECOURS
WHERE
    GROUPECOURS.SIGLE
NOT IN (
  SELECT
    DISTINCT(SIGLE)
  FROM
    GROUPECOURS
  WHERE
    CODEPROFESSEUR = (
      SELECT
          CODEPROFESSEUR
      FROM
          PROFESSEUR
      WHERE
          NOM = 'Galois' AND PRENOM = 'Evariste'
      AND
          ROWNUM = 1
  )
);
-- Req 8
SELECT
    MOYENNE1, MOYENNE2, MOYENNE1-MOYENNE2 AS DIFF
FROM (
    SELECT
        ROUND(AVG(NOTE), 2) AS MOYENNE1
    FROM
        INSCRIPTION
    WHERE
        CODESESSION = '32003'
), (
    SELECT
         ROUND(AVG(NOTE), 2) AS MOYENNE2
    FROM
        INSCRIPTION
    WHERE
        CODESESSION = '12004'
);
-- Req 9
SELECT BASE.SIGLE, BASE.TITRE, MAX(DIFF) AS DIFF FROM (
    SELECT
        INSCRIPTION.CODESESSION, INSCRIPTION.SIGLE, COURS.TITRE
    FROM
        INSCRIPTION, GROUPECOURS, COURS
    WHERE
        INSCRIPTION.SIGLE = GROUPECOURS.SIGLE
    AND
        INSCRIPTION.NOGROUPE = GROUPECOURS.NOGROUPE
    AND
        INSCRIPTION.CODESESSION = GROUPECOURS.CODESESSION
    AND
        GROUPECOURS.SIGLE = COURS.SIGLE
) BASE
JOIN (
    SELECT
        MAX(NOTE), MIN(NOTE), MAX(NOTE) - MIN(NOTE) AS DIFF, SIGLE, NOGROUPE, CODESESSION
    FROM
        INSCRIPTION
    GROUP BY
        SIGLE, NOGROUPE, CODESESSION
) NOTES
ON
    NOTES.SIGLE = BASE.SIGLE
GROUP BY
    BASE.SIGLE, BASE.TITRE;
-- Req 10
UPDATE SESSIONUQAM
SET
    SESSIONUQAM.DATEFIN = '22/12/2003'
WHERE
    SESSIONUQAM.CODESESSION
IN (
    SELECT
        CODESESSION
    FROM (
        SELECT
            AVG(NOTE) AS MOYENNE, SIGLE, CODESESSION, NOGROUPE
        FROM
            INSCRIPTION
        WHERE
            CODESESSION = '32003'
        GROUP BY
            SIGLE, CODESESSION, NOGROUPE
    )
    WHERE
        MOYENNE >= 80
);
-- Req 11
ALTER TABLE INSCRIPTION DROP COLUMN DATEABANDON;
ALTER TABLE GROUPECOURS DROP COLUMN MAXINSCRIPTIONS;
SELECT * FROM INSCRIPTION;
SELECT * FROM GROUPECOURS;
-- Req 12
DELETE
FROM
    INSCRIPTION
WHERE
    CODEPERMANENT IN (
        SELECT
            CODEPERMANENT
        FROM
            ETUDIANT
        WHERE
            ETUDIANT.NOM NOT LIKE 'T%'
    );
DELETE
FROM
    ETUDIANT
WHERE
    ETUDIANT.NOM NOT LIKE 'T%';
SELECT * FROM INSCRIPTION;
SELECT * FROM ETUDIANT;
SPOOL OFF;